name: Medtask
description: Aplicativo Flutter para controle de remédios com notificações.
publish_to: 'none' # remove se for publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  sqflite: ^2.3.3
  path: ^1.9.0
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.3
  android_intent_plus: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: []
