name: Medtask
description: Aplicativo Flutter para controle de remédios com notificações.
publish_to: 'none' # remove se for publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: any
  sqflite: ^2.3.3
  path: ^1.9.0
  awesome_notifications: any
  android_intent_plus: ^5.0.2
  shared_preferences: ^2.2.3
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: []
